use clap::Parser;
use konf_init::config::{ProjectConfig, ToolsConfig, TriggerConfig};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// Name of the new kell
    #[arg(short, long)]
    name: String,

    /// Description of the new kell
    #[arg(short, long)]
    description: Option<String>,

    /// Capabilities to grant to the default chat trigger (comma-separated)
    #[arg(short, long, default_value = "ai:complete,memory:*")]
    capabilities: String,

    /// Output directory
    #[arg(short, long, default_value = ".")]
    out_dir: PathBuf,
}

fn main() -> anyhow::Result<()> {
    let args = Args::parse();

    let kell_dir = args.out_dir.join(&args.name);
    let config_dir = kell_dir.join("config");
    let workflows_dir = config_dir.join("workflows");
    let prompts_dir = kell_dir.join("prompts");

    println!(
        "Scaffolding new kell '{}' in {}...",
        args.name,
        kell_dir.display()
    );

    // 1. Create directories
    fs::create_dir_all(&workflows_dir)?;
    fs::create_dir_all(&prompts_dir)?;

    // 2. Create project.yaml
    let caps: Vec<String> = args
        .capabilities
        .split(',')
        .map(|s| s.trim().to_string())
        .collect();

    let mut triggers = HashMap::new();
    triggers.insert(
        "chat".to_string(),
        TriggerConfig {
            workflow: "chat".to_string(),
            capabilities: caps,
        },
    );

    let project = ProjectConfig {
        name: args.name.clone(),
        description: args.description,
        version: "0.1.0".into(),
        triggers,
    };

    let project_yaml = serde_yaml::to_string(&project)?;
    fs::write(config_dir.join("project.yaml"), project_yaml)?;

    // 3. Create tools.yaml (Minimal default)
    let tools = ToolsConfig {
        llm: Some(serde_json::json!({
            "provider": "openai",
            "model": "${KONF_MODEL:-qwen3:8b}"
        })),
        ..Default::default()
    };

    let tools_yaml = serde_yaml::to_string(&tools)?;
    fs::write(config_dir.join("tools.yaml"), tools_yaml)?;

    // 4. Create default chat workflow
    let chat_workflow = r#"workflow: chat
description: "Default chat workflow generated by konf-init-kell"
nodes:
  respond:
    do: ai:complete
    with:
      prompt: "{{ input.message }}"
    return: true
"#;
    fs::write(workflows_dir.join("chat.yaml"), chat_workflow)?;

    // 5. Create basic README
    let readme = format!(
        r#"# {name}

This is a Konf Kell (AI Agent).

## Identity
{description}

## How to run
```bash
KONF_CONFIG_DIR=./config cargo run --bin konf-backend
```
"#,
        name = args.name,
        description = project.description.as_deref().unwrap_or("A Konf agent.")
    );

    fs::write(kell_dir.join("README.md"), readme)?;

    println!("Success! New kell '{}' ready.", args.name);
    Ok(())
}
