//! redb-backed journal implementation.
//!
//! Layout (three tables inside one redb database):
//!
//! - `events`: `u64` sequence id → postcard-encoded [`StoredEntry`].
//!   The primary log. Sequences are monotonic and dense.
//! - `by_run`: `(RunIdBytes, u64)` → `()`. Compound-key index that lets us
//!   list every sequence for a specific run via a range scan.
//! - `by_session`: `(SessionKey, u64)` → `()`. Compound-key index that lets
//!   us list every sequence for a specific session via a range scan.
//!
//! Sequence ids are generated by a single-writer transaction that reads the
//! current tail of `events`, adds one, and inserts. MVCC means readers are
//! never blocked by this.
//!
//! All redb operations are synchronous; the async trait methods wrap them in
//! [`tokio::task::spawn_blocking`] to keep the tokio scheduler responsive.

use std::path::Path;
use std::sync::Arc;

use chrono::{TimeZone, Utc};
use redb::{
    Database, MultimapTableDefinition, ReadableDatabase, ReadableTable, TableDefinition,
};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::{JournalEntry, JournalError, JournalRow, JournalStore};
use crate::error::RunId;

// ---------------------------------------------------------------------------
// Table definitions
// ---------------------------------------------------------------------------

/// Primary log: sequence id → postcard(StoredEntry).
///
/// The value is `&[u8]` because redb's built-in codecs don't know about our
/// types; we serialize with postcard and store the bytes directly.
const EVENTS: TableDefinition<u64, &[u8]> = TableDefinition::new("journal_events");

/// Multimap index: run id (16 bytes) → set of sequence ids for that run.
const BY_RUN: MultimapTableDefinition<&[u8], u64> = MultimapTableDefinition::new("journal_by_run");

/// Multimap index: session id (bytes) → set of sequence ids for that session.
const BY_SESSION: MultimapTableDefinition<&str, u64> =
    MultimapTableDefinition::new("journal_by_session");

// ---------------------------------------------------------------------------
// Stored value shape
// ---------------------------------------------------------------------------

/// On-disk representation of one journal event. Stored as postcard bytes.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct StoredEntry {
    run_id_bytes: [u8; 16],
    session_id: String,
    namespace: String,
    event_type: String,
    payload_json: String, // serde_json::Value serialized to its canonical string form
    created_at_micros: i64,
}

impl StoredEntry {
    fn from_entry(entry: &JournalEntry) -> Result<Self, JournalError> {
        Ok(Self {
            run_id_bytes: *entry.run_id.as_bytes(),
            session_id: entry.session_id.clone(),
            namespace: entry.namespace.clone(),
            event_type: entry.event_type.clone(),
            payload_json: serde_json::to_string(&entry.payload).map_err(JournalError::serialization)?,
            created_at_micros: Utc::now().timestamp_micros(),
        })
    }

    fn into_row(self, id: u64) -> Result<JournalRow, JournalError> {
        let run_id = Uuid::from_bytes(self.run_id_bytes);
        let payload = serde_json::from_str(&self.payload_json).map_err(JournalError::serialization)?;
        let created_at = Utc
            .timestamp_micros(self.created_at_micros)
            .single()
            .unwrap_or_else(Utc::now);
        Ok(JournalRow {
            id,
            run_id,
            session_id: self.session_id,
            namespace: self.namespace,
            event_type: self.event_type,
            payload,
            created_at,
        })
    }
}

// ---------------------------------------------------------------------------
// RedbJournal
// ---------------------------------------------------------------------------

/// redb-backed [`JournalStore`] implementation.
///
/// Cheap to clone (holds `Arc<Database>` internally).
#[derive(Clone)]
pub struct RedbJournal {
    db: Arc<Database>,
}

impl RedbJournal {
    /// Open (or create) a standalone redb database at `path` and return a
    /// journal backed by it. Tables are created on first use.
    ///
    /// Prefer constructing via [`crate::storage::KonfStorage`] when the
    /// journal shares a database handle with the scheduler and runner
    /// intent store.
    pub async fn open(path: impl AsRef<Path>) -> Result<Self, JournalError> {
        let path = path.as_ref().to_path_buf();
        let db = tokio::task::spawn_blocking(move || Database::create(&path))
            .await
            .map_err(|e| JournalError::storage(std::io::Error::other(e)))?
            .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
        Self::from_database(Arc::new(db))
    }

    /// Build a journal over an already-opened shared [`Database`]. Used by
    /// [`crate::storage::KonfStorage`].
    pub fn from_database(db: Arc<Database>) -> Result<Self, JournalError> {
        // Ensure tables exist so later read transactions don't fail with
        // "table does not exist". redb creates tables lazily on first
        // write open; we open+commit once to materialize them.
        let write = db
            .begin_write()
            .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
        {
            let _ = write
                .open_table(EVENTS)
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let _ = write
                .open_multimap_table(BY_RUN)
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let _ = write
                .open_multimap_table(BY_SESSION)
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
        }
        write
            .commit()
            .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
        Ok(Self { db })
    }

    /// Access the shared database handle (used by sibling stores in
    /// [`crate::storage::KonfStorage`]).
    pub fn database(&self) -> Arc<Database> {
        self.db.clone()
    }
}

#[async_trait::async_trait]
impl JournalStore for RedbJournal {
    async fn append(&self, entry: JournalEntry) -> Result<u64, JournalError> {
        let db = self.db.clone();
        let stored = StoredEntry::from_entry(&entry)?;
        let bytes = postcard::to_allocvec(&stored).map_err(JournalError::serialization)?;

        tokio::task::spawn_blocking(move || -> Result<u64, JournalError> {
            let write = db
                .begin_write()
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let next_id = {
                let mut events = write
                    .open_table(EVENTS)
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
                let next_id = events
                    .iter()
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?
                    .next_back()
                    .transpose()
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?
                    .map(|(k, _)| k.value() + 1)
                    .unwrap_or(1);
                events
                    .insert(next_id, bytes.as_slice())
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
                next_id
            };
            {
                let mut by_run = write
                    .open_multimap_table(BY_RUN)
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
                by_run
                    .insert(stored.run_id_bytes.as_slice(), next_id)
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            }
            {
                let mut by_session = write
                    .open_multimap_table(BY_SESSION)
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
                by_session
                    .insert(stored.session_id.as_str(), next_id)
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            }
            write
                .commit()
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            Ok(next_id)
        })
        .await
        .map_err(|e| JournalError::storage(std::io::Error::other(e)))?
    }

    async fn query_by_run(&self, run_id: RunId) -> Result<Vec<JournalRow>, JournalError> {
        let db = self.db.clone();
        let run_id_bytes = *run_id.as_bytes();
        tokio::task::spawn_blocking(move || -> Result<Vec<JournalRow>, JournalError> {
            let read = db
                .begin_read()
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let by_run = read
                .open_multimap_table(BY_RUN)
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let events = read
                .open_table(EVENTS)
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;

            let ids_iter = by_run
                .get(run_id_bytes.as_slice())
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let mut rows = Vec::new();
            for id_res in ids_iter {
                let id = id_res
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?
                    .value();
                if let Some(stored_bytes) = events
                    .get(id)
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?
                {
                    let stored: StoredEntry = postcard::from_bytes(stored_bytes.value())
                        .map_err(JournalError::serialization)?;
                    rows.push(stored.into_row(id)?);
                }
            }
            rows.sort_by_key(|r| r.id);
            Ok(rows)
        })
        .await
        .map_err(|e| JournalError::storage(std::io::Error::other(e)))?
    }

    async fn query_by_session(
        &self,
        session_id: &str,
        limit: usize,
    ) -> Result<Vec<JournalRow>, JournalError> {
        let db = self.db.clone();
        let session_id = session_id.to_string();
        tokio::task::spawn_blocking(move || -> Result<Vec<JournalRow>, JournalError> {
            let read = db
                .begin_read()
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let by_session = read
                .open_multimap_table(BY_SESSION)
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let events = read
                .open_table(EVENTS)
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;

            // Collect all sequences for this session, then pick the most
            // recent `limit` (sequences are monotonic by time so last N is
            // newest N).
            let ids_iter = by_session
                .get(session_id.as_str())
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let mut ids: Vec<u64> = Vec::new();
            for id_res in ids_iter {
                ids.push(
                    id_res
                        .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?
                        .value(),
                );
            }
            ids.sort_unstable();
            if ids.len() > limit {
                let start = ids.len() - limit;
                ids.drain(..start);
            }
            // Return newest first to match the old Postgres
            // `ORDER BY created_at DESC LIMIT N` semantics.
            ids.reverse();

            let mut rows = Vec::with_capacity(ids.len());
            for id in ids {
                if let Some(stored_bytes) = events
                    .get(id)
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?
                {
                    let stored: StoredEntry = postcard::from_bytes(stored_bytes.value())
                        .map_err(JournalError::serialization)?;
                    rows.push(stored.into_row(id)?);
                }
            }
            Ok(rows)
        })
        .await
        .map_err(|e| JournalError::storage(std::io::Error::other(e)))?
    }

    async fn recent(&self, limit: usize) -> Result<Vec<JournalRow>, JournalError> {
        let db = self.db.clone();
        tokio::task::spawn_blocking(move || -> Result<Vec<JournalRow>, JournalError> {
            let read = db
                .begin_read()
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let events = read
                .open_table(EVENTS)
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            let mut rows = Vec::with_capacity(limit.min(1024));
            let iter = events
                .iter()
                .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
            for pair in iter.rev().take(limit) {
                let (id_guard, val_guard) =
                    pair.map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
                let id = id_guard.value();
                let stored: StoredEntry =
                    postcard::from_bytes(val_guard.value()).map_err(JournalError::serialization)?;
                rows.push(stored.into_row(id)?);
            }
            Ok(rows)
        })
        .await
        .map_err(|e| JournalError::storage(std::io::Error::other(e)))?
    }

    async fn reconcile_zombies(&self) -> Result<u64, JournalError> {
        // Single scan of `events` to build two sets:
        //   started:  run_id → (session_id, namespace) for "workflow_started"
        //   terminal: set of run_ids with any terminal event
        // Then for every started-but-not-terminal run, append a synthetic
        // `workflow_failed` event with `reconciled: true`.
        let db = self.db.clone();

        // Phase 1: scan under spawn_blocking
        let zombies: Vec<JournalEntry> = tokio::task::spawn_blocking(
            move || -> Result<Vec<JournalEntry>, JournalError> {
                use std::collections::{HashMap, HashSet};
                let read = db
                    .begin_read()
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
                let events = read
                    .open_table(EVENTS)
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;

                let mut started: HashMap<[u8; 16], (String, String)> = HashMap::new();
                let mut terminal: HashSet<[u8; 16]> = HashSet::new();

                let iter = events
                    .iter()
                    .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
                for pair in iter {
                    let (_id, val_guard) = pair
                        .map_err(|e| JournalError::storage(std::io::Error::other(e.to_string())))?;
                    let stored: StoredEntry = postcard::from_bytes(val_guard.value())
                        .map_err(JournalError::serialization)?;
                    match stored.event_type.as_str() {
                        "workflow_started" => {
                            started
                                .entry(stored.run_id_bytes)
                                .or_insert((stored.session_id, stored.namespace));
                        }
                        "workflow_completed" | "workflow_failed" | "workflow_cancelled" => {
                            terminal.insert(stored.run_id_bytes);
                        }
                        _ => {}
                    }
                }
                let mut result = Vec::new();
                for (run_id_bytes, (session_id, namespace)) in started {
                    if !terminal.contains(&run_id_bytes) {
                        result.push(JournalEntry {
                            run_id: Uuid::from_bytes(run_id_bytes),
                            session_id,
                            namespace,
                            event_type: "workflow_failed".into(),
                            payload: serde_json::json!({
                                "error": "System restart — workflow was interrupted",
                                "reconciled": true,
                            }),
                        });
                    }
                }
                Ok(result)
            },
        )
        .await
        .map_err(|e| JournalError::storage(std::io::Error::other(e)))??;

        // Phase 2: append the reconciliation events via the normal path.
        let count = zombies.len() as u64;
        for entry in zombies {
            self.append(entry).await?;
        }
        Ok(count)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    async fn journal() -> (RedbJournal, tempfile::TempDir) {
        let dir = tempdir().unwrap();
        let path = dir.path().join("journal.redb");
        let j = RedbJournal::open(&path).await.unwrap();
        (j, dir)
    }

    fn entry(run_id: Uuid, session: &str, event_type: &str) -> JournalEntry {
        JournalEntry {
            run_id,
            session_id: session.into(),
            namespace: "konf:test:user".into(),
            event_type: event_type.into(),
            payload: serde_json::json!({}),
        }
    }

    #[tokio::test]
    async fn append_and_query_by_run() {
        let (j, _dir) = journal().await;
        let run_id = Uuid::new_v4();
        let id1 = j.append(entry(run_id, "s1", "workflow_started")).await.unwrap();
        let id2 = j.append(entry(run_id, "s1", "workflow_completed")).await.unwrap();
        assert!(id2 > id1);

        let rows = j.query_by_run(run_id).await.unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].event_type, "workflow_started");
        assert_eq!(rows[1].event_type, "workflow_completed");
        assert_eq!(rows[0].run_id, run_id);
    }

    #[tokio::test]
    async fn query_by_session_respects_limit() {
        let (j, _dir) = journal().await;
        let run1 = Uuid::new_v4();
        let run2 = Uuid::new_v4();
        j.append(entry(run1, "sess", "workflow_started")).await.unwrap();
        j.append(entry(run2, "sess", "workflow_started")).await.unwrap();
        j.append(entry(run2, "sess", "workflow_completed")).await.unwrap();

        let rows = j.query_by_session("sess", 2).await.unwrap();
        assert_eq!(rows.len(), 2);
        // Newest-first ordering
        assert_eq!(rows[0].event_type, "workflow_completed");
    }

    #[tokio::test]
    async fn recent_returns_newest_first() {
        let (j, _dir) = journal().await;
        for i in 0..5 {
            j.append(entry(Uuid::new_v4(), &format!("s{i}"), "workflow_started"))
                .await
                .unwrap();
        }
        let rows = j.recent(3).await.unwrap();
        assert_eq!(rows.len(), 3);
        // Descending ids
        assert!(rows[0].id > rows[1].id);
        assert!(rows[1].id > rows[2].id);
    }

    #[tokio::test]
    async fn reconcile_zombies_marks_unterminated_runs_failed() {
        let (j, _dir) = journal().await;
        let live = Uuid::new_v4();
        let done = Uuid::new_v4();
        j.append(entry(live, "s1", "workflow_started")).await.unwrap();
        j.append(entry(done, "s2", "workflow_started")).await.unwrap();
        j.append(entry(done, "s2", "workflow_completed")).await.unwrap();

        let count = j.reconcile_zombies().await.unwrap();
        assert_eq!(count, 1);

        let rows = j.query_by_run(live).await.unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[1].event_type, "workflow_failed");
        assert_eq!(rows[1].payload["reconciled"], serde_json::json!(true));
    }
}
